name: Train Carts
main: com.bergerkiller.bukkit.tc.TrainCarts
version: 1.71.3
author: bergerkiller
description: Plugin that allows the use of minecart trains with adjustable settings
depend: [BKCommonLib]
softdepend: [MinecartManiaCore, SignLink, My Worlds]
commands:
    train:
        description: Perform TrainCarts commands for complete trains
        usage: See development or WIKI page of TrainCarts
    cart:
        description: Perform TrainCarts commands for single minecarts
        usage: See development or WIKI page of TrainCarts